### ISSUE TITLE
how to use pagingStore and ThemeStore 

### ISSUE THREAD

**Issue by Avi-ADAM** [mediakular/gridcraft#12]
thank you for this library its amazing!
when i import pagingStore and ThemeStore  from "@mediakular/gridcraft"; i get error `SyntaxError: The requested module '/node_modules/.vite/deps/@mediakular_gridcraft.js?v=17d98e51' does not provide an export named 'PagingStore' (at +page.svelte:4:19)` withot it i didnt manege to get paging and the footer to work also i cannot change theme.

**Comment by st3v3y** [comment]
Hey @Avi-ADAM, thanks for your question. I am happy to hear that you like the library!

I realized that the documentation was outdated because the last website deployment wasn't successful. 
Now you can follow the updated documentation here: https://gridcraft.mediakular.com/docs/paging 

Here also some examples on how to implement paging: 

Simple: https://www.sveltelab.dev/jj9lpokeuet9223
More advanced with custom paging: https://www.sveltelab.dev/dl77tkzvr65ustm
Example for paging with page number buttons: https://www.sveltelab.dev/97vvmq174sei27p

Let me know if everything works now and if you have any further questions

**Comment by Avi-ADAM** [comment]
Thank you!
With the new documentation its works great, thank for this repository
